-- Lab 37 — schema and deterministic seed for PostgreSQL.
--
-- Run it through ../seed.sh, which passes the scale:
--   small   100 000 customers,   500 000 orders  (~1.8 M order lines)  — tests and quick tries
--   medium  1 000 000 customers, 5 000 000 orders (~18 M order lines)  — the numbers in Chapter 37
--   large   2 000 000 customers, 20 000 000 orders (~72 M order lines) — if you have the disk
--
-- Every "random" value is a hash of the row's key, so every reader gets exactly the same
-- rows, the same statistics and — on the same PostgreSQL version — the same plans.
-- The data is skewed on purpose, the way real data is:
--   * customer 1 is a marketplace account that places 5% of all orders;
--   * customers 2–11 are B2B key accounts: 5% of orders between them, 10–40 lines each;
--   * product 1 is a bestseller in 8% of all order lines, products 2–101 share another 10%;
--   * country and city are correlated (Berlin only exists in DE);
--   * emails are stored in mixed case ("Anna.Kowalski42@Example.com").
-- The lab clock is fixed at 2026-09-01 00:00 UTC (table lab_clock); orders cover the three
-- years before it, so date-range queries behave the same whenever you run them.

\set ON_ERROR_STOP on
\timing on

\if :{?scale}
\else
  \set scale medium
\endif

SELECT CASE :'scale' WHEN 'small' THEN 100000 WHEN 'medium' THEN 1000000 WHEN 'large' THEN 2000000 END AS n_customers,
       CASE :'scale' WHEN 'small' THEN 500000 WHEN 'medium' THEN 5000000 WHEN 'large' THEN 20000000 END AS n_orders,
       50000 AS n_products
\gset

\if :{?n_customers}
\else
  \echo 'unknown scale: use small, medium or large'
  \quit
\endif

\echo Seeding scale :scale — :n_customers customers, :n_orders orders, :n_products products

-- ---------------------------------------------------------------------------
-- Schema (dropped and recreated: seeding is repeatable)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS shipments, order_lines, orders, products, customers, lab_clock CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE TABLE lab_clock (now timestamptz NOT NULL);
INSERT INTO lab_clock VALUES ('2026-09-01 00:00:00+00');

CREATE TABLE customers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       text        NOT NULL,
    name        text        NOT NULL,
    country     text        NOT NULL,          -- ISO 3166-1 alpha-2
    city        text        NOT NULL,
    tier        text        NOT NULL,          -- consumer | key_account | marketplace
    created_at  timestamptz NOT NULL
);

CREATE TABLE products (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku       text          NOT NULL,
    name      text          NOT NULL,
    category  text          NOT NULL,
    price     numeric(10,2) NOT NULL
);

CREATE TABLE orders (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    bigint        NOT NULL,
    status         text          NOT NULL,     -- open | paid | shipped | cancelled
    created_at     timestamptz   NOT NULL,
    total          numeric(12,2) NOT NULL,
    currency       char(3)       NOT NULL,
    shipping_note  text
);

CREATE TABLE order_lines (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    bigint        NOT NULL,
    product_id  bigint        NOT NULL,
    quantity    integer       NOT NULL,
    unit_price  numeric(10,2) NOT NULL
);

CREATE TABLE shipments (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       bigint      NOT NULL,
    carrier        text        NOT NULL,
    shipped_at     timestamptz NOT NULL,
    tracking_code  text        NOT NULL
);

-- ---------------------------------------------------------------------------
-- Deterministic generators (inlined by the planner, so they cost almost nothing)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pg_temp.r(k bigint, salt int) RETURNS float8
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT (hashint8extended(k, salt) & 2147483647)::float8 / 2147483648.0 $$;

-- Which customer placed order o: 5% the marketplace, 5% the key accounts, 90% everyone else.
CREATE OR REPLACE FUNCTION pg_temp.customer_of(o bigint, n_customers bigint) RETURNS bigint
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT CASE WHEN pg_temp.r(o, 1) < 0.05 THEN 1
                  WHEN pg_temp.r(o, 1) < 0.10 THEN 2 + floor(pg_temp.r(o, 2) * 10)::bigint
                  ELSE 12 + floor(pg_temp.r(o, 3) * (n_customers - 11))::bigint END $$;

CREATE OR REPLACE FUNCTION pg_temp.lines_of(o bigint) RETURNS int
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT CASE WHEN pg_temp.r(o, 1) < 0.05 THEN 1 + floor(pg_temp.r(o, 11) * 3)::int     -- marketplace: 1–3
                  WHEN pg_temp.r(o, 1) < 0.10 THEN 10 + floor(pg_temp.r(o, 11) * 31)::int   -- key account: 10–40
                  ELSE 1 + floor(pg_temp.r(o, 11) * 4)::int END $$;                         -- consumer: 1–4

-- Line k of order o. o * 64 + k is unique because an order has at most 40 lines.
CREATE OR REPLACE FUNCTION pg_temp.product_of(o bigint, k int, n_products bigint) RETURNS bigint
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT CASE WHEN pg_temp.r(o * 64 + k, 12) < 0.08 THEN 1
                  WHEN pg_temp.r(o * 64 + k, 12) < 0.18 THEN 2 + floor(pg_temp.r(o * 64 + k, 13) * 100)::bigint
                  ELSE 102 + floor(pg_temp.r(o * 64 + k, 14) * (n_products - 101))::bigint END $$;

CREATE OR REPLACE FUNCTION pg_temp.qty_of(o bigint, k int) RETURNS int
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT CASE WHEN pg_temp.r(o, 1) >= 0.05 AND pg_temp.r(o, 1) < 0.10
                  THEN 1 + floor(pg_temp.r(o * 64 + k, 15) * 50)::int
                  ELSE 1 + floor(pg_temp.r(o * 64 + k, 15) * 3)::int END $$;

CREATE OR REPLACE FUNCTION pg_temp.price_of(p bigint) RETURNS numeric
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT round((5 + pg_temp.r(p, 21) * 495)::numeric, 2) $$;

-- Orders are spread evenly over the three years before the lab clock, in id order.
CREATE OR REPLACE FUNCTION pg_temp.created_of(o bigint, n_orders bigint) RETURNS timestamptz
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT timestamptz '2023-09-01 00:00:00+00'
             + ((o - 1 + pg_temp.r(o, 41)) / n_orders) * interval '1096 days' $$;

-- Recent orders are mostly open or paid; old ones are mostly shipped.
CREATE OR REPLACE FUNCTION pg_temp.status_of(o bigint, n_orders bigint) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT CASE WHEN pg_temp.created_of(o, n_orders) >= timestamptz '2026-08-02 00:00:00+00' THEN
                    CASE WHEN pg_temp.r(o, 51) < 0.40 THEN 'open' WHEN pg_temp.r(o, 51) < 0.70 THEN 'paid'
                         WHEN pg_temp.r(o, 51) < 0.95 THEN 'shipped' ELSE 'cancelled' END
                  ELSE
                    CASE WHEN pg_temp.r(o, 51) < 0.01 THEN 'open' WHEN pg_temp.r(o, 51) < 0.02 THEN 'paid'
                         WHEN pg_temp.r(o, 51) < 0.95 THEN 'shipped' ELSE 'cancelled' END
             END $$;

-- ---------------------------------------------------------------------------
-- Data
-- ---------------------------------------------------------------------------
\echo customers
INSERT INTO customers (id, email, name, country, city, tier, created_at)
SELECT c,
       f || '.' || l || c || '@' || d,
       f || ' ' || l,
       (ARRAY['DE','PL','UA','FR','ES','IT','US','NL'])[ci],
       (ARRAY['Berlin','Hamburg','Munich','Cologne','Frankfurt',
              'Warsaw','Krakow','Wroclaw','Gdansk','Poznan',
              'Kyiv','Lviv','Kharkiv','Odesa','Dnipro',
              'Paris','Lyon','Marseille','Toulouse','Lille',
              'Madrid','Barcelona','Valencia','Seville','Bilbao',
              'Rome','Milan','Naples','Turin','Bologna',
              'New York','Chicago','Austin','Seattle','Boston',
              'Amsterdam','Rotterdam','Utrecht','The Hague','Eindhoven'])[(ci - 1) * 5 + cy],
       CASE WHEN c = 1 THEN 'marketplace' WHEN c <= 11 THEN 'key_account' ELSE 'consumer' END,
       timestamptz '2021-09-01 00:00:00+00' + pg_temp.r(c, 6) * interval '1826 days'
FROM generate_series(1, :n_customers) AS c,
LATERAL (SELECT
    (ARRAY['Anna','Olena','Maria','Sofia','Emma','Julia','Kateryna','Laura','Marta','Nina',
           'Iryna','Eva','Lena','Clara','Ines','Chloe','Olivia','Mia','Zoe','Alicia',
           'Andriy','Oleksandr','Jan','Piotr','Tomasz','Lukas','Jonas','Max','Paul','Lucas',
           'Hugo','Leo','Marco','Luca','Pablo','Diego','James','Noah','Ethan','Daniel'])[1 + floor(pg_temp.r(c, 1) * 40)::int] AS f,
    (ARRAY['Kowalski','Nowak','Wisniewski','Wojcik','Kowalczyk','Kaminski','Lewandowski','Zielinski','Szymanski','Wozniak',
           'Shevchenko','Kovalenko','Bondarenko','Tkachenko','Kravchenko','Melnyk','Boyko','Koval','Oliynyk','Moroz',
           'Mueller','Schmidt','Schneider','Fischer','Weber','Meyer','Wagner','Becker','Schulz','Hoffmann',
           'Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau',
           'Garcia','Fernandez','Gonzalez','Rodriguez','Lopez','Martinez','Sanchez','Perez','Gomez','Diaz',
           'Rossi','Russo','Ferrari','Esposito','Bianchi','Romano','Colombo','Ricci','Marino','Greco',
           'Smith','Johnson','Williams','Brown','Jones','Miller','Davis','Wilson','Anderson','Taylor',
           'DeJong','Jansen','DeVries','VanDenBerg','VanDijk','Bakker','Janssen','Visser','Smit','Meijer',
           'Novak','Horvat','Kovacs','Nagy','Popescu','Ionescu','Petrov','Ivanov','Svoboda','Dvorak',
           'Larsen','Hansen','Nielsen','Jensen','Andersen','Berg','Lund','Holm','Strand','Dahl'])[1 + floor(pg_temp.r(c, 2) * 100)::int] AS l,
    (ARRAY['Example.com','Mail.test','Corp.example'])[1 + floor(pg_temp.r(c, 3) * 3)::int] AS d,
    width_bucket(pg_temp.r(c, 4), ARRAY[0.20, 0.35, 0.50, 0.62, 0.72, 0.82, 0.92]::float8[]) + 1 AS ci,
    width_bucket(pg_temp.r(c, 5), ARRAY[0.40, 0.65, 0.80, 0.90]::float8[]) + 1 AS cy
) AS x;

\echo products
INSERT INTO products (id, sku, name, category, price)
SELECT p,
       'SKU-' || lpad(p::text, 6, '0'),
       (ARRAY['Oak','Steel','Linen','Cotton','Glass','Walnut','Copper','Bamboo','Wool','Marble'])[1 + floor(pg_temp.r(p, 31) * 10)::int]
         || ' ' ||
       (ARRAY['desk','lamp','chair','shelf','mug','rug','kettle','vase','cabinet','stool'])[1 + floor(pg_temp.r(p, 32) * 10)::int]
         || ' ' || p,
       (ARRAY['furniture','lighting','kitchen','textiles','decor'])[1 + floor(pg_temp.r(p, 33) * 5)::int],
       pg_temp.price_of(p)
FROM generate_series(1, :n_products) AS p;

\echo order_lines
INSERT INTO order_lines (order_id, product_id, quantity, unit_price)
SELECT o, pg_temp.product_of(o, k, :n_products), pg_temp.qty_of(o, k),
       pg_temp.price_of(pg_temp.product_of(o, k, :n_products))
FROM generate_series(1, :n_orders) AS o,
     generate_series(1, pg_temp.lines_of(o)) AS k;

\echo orders
INSERT INTO orders (id, customer_id, status, created_at, total, currency, shipping_note)
SELECT o,
       pg_temp.customer_of(o, :n_customers),
       pg_temp.status_of(o, :n_orders),
       pg_temp.created_of(o, :n_orders),
       (SELECT sum(pg_temp.qty_of(o, k) * pg_temp.price_of(pg_temp.product_of(o, k, :n_products)))
          FROM generate_series(1, pg_temp.lines_of(o)) AS k),
       'EUR',
       CASE WHEN pg_temp.r(o, 61) < 0.10 THEN 'Leave with the neighbour if nobody answers' END
FROM generate_series(1, :n_orders) AS o;

\echo shipments
INSERT INTO shipments (order_id, carrier, shipped_at, tracking_code)
SELECT o,
       (ARRAY['DHL','UPS','DPD','GLS','Nova Poshta'])[1 + floor(pg_temp.r(o * 8 + s, 71) * 5)::int],
       pg_temp.created_of(o, :n_orders) + (1 + pg_temp.r(o * 8 + s, 72) * 4) * interval '1 day',
       md5((o * 8 + s)::text)
FROM generate_series(1, :n_orders) AS o,
     generate_series(1, CASE WHEN pg_temp.r(o, 1) >= 0.05 AND pg_temp.r(o, 1) < 0.10
                             THEN 2 + floor(pg_temp.r(o, 73) * 5)::int ELSE 1 END) AS s
WHERE pg_temp.status_of(o, :n_orders) = 'shipped';

-- Identity columns: continue after the seeded ids.
SELECT setval(pg_get_serial_sequence('customers', 'id'), (SELECT max(id) FROM customers));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT max(id) FROM products));
SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT max(id) FROM orders));

-- ---------------------------------------------------------------------------
-- The baseline indexes — what a typical team would have. Some of them are the lab.
-- ---------------------------------------------------------------------------
\echo indexes and foreign keys
CREATE UNIQUE INDEX uq_customers_email ON customers (email);          -- case-sensitive
CREATE UNIQUE INDEX uq_products_sku ON products (sku);
-- Someone replaced the foreign-key index on orders.customer_id with this one, reasoning that
-- "it contains customer_id, so it covers it". It also serves ORDER BY created_at.
CREATE INDEX ix_orders_created_at_customer_id ON orders (created_at, customer_id);
CREATE INDEX ix_order_lines_order_id ON order_lines (order_id);
CREATE INDEX ix_order_lines_product_id ON order_lines (product_id);
CREATE INDEX ix_shipments_order_id ON shipments (order_id);
CREATE INDEX ix_customers_country_city ON customers (country, city);

ALTER TABLE orders      ADD CONSTRAINT fk_orders_customers      FOREIGN KEY (customer_id) REFERENCES customers (id);
ALTER TABLE order_lines ADD CONSTRAINT fk_order_lines_orders    FOREIGN KEY (order_id)    REFERENCES orders (id);
ALTER TABLE order_lines ADD CONSTRAINT fk_order_lines_products  FOREIGN KEY (product_id)  REFERENCES products (id);
ALTER TABLE shipments   ADD CONSTRAINT fk_shipments_orders      FOREIGN KEY (order_id)    REFERENCES orders (id);

-- Fresh statistics and a fresh visibility map, so every reader starts from the same place.
\echo vacuum analyze
VACUUM (ANALYZE) customers, products, orders, order_lines, shipments;

SELECT relname AS "table", n_live_tup AS "rows", pg_size_pretty(pg_total_relation_size(relid)) AS "size incl. indexes"
FROM pg_stat_user_tables ORDER BY relname;
